### ISSUE TITLE
How to attach attachment to the email?

### ISSUE THREAD

**Issue by muzammilaskari** [rdok/elasticemail-php#16]
Hi,
I am working with your package, and it works great, but I need to know how do I attach an attachment to the email which I am sending, 
Your quick response will be highly appriciated.
Thanks,

**Comment by rdok** [comment]
Reopening pending new minor release.

**Comment by muzammilaskari** [comment]
Hi, Can you please share code snippest which shows how to add attachments to the email?
Currently I am using this coe
` $elasticEmail->email()->send([
                'to'       => $recipient,
                'subject'  => $request->subject,
                'body'     => $request->description,
                'from'     => env('ADVERTISING_MAIL_FROM_ADDRESS')
            ]);`

**Comment by rdok** [comment]
Thanks for highlighting this feature @muzammilaskari 

Upgrade your version to latest release `v2.2.0`. This includes said feature. 

Example usage, taken from [integration tests](https://github.com/rdok/elasticemail-php/blob/3166f35a437372e7c19161668eaa6f8fc22674d8/tests/Integration/Email/SendTest.php#L32)

```php
       $subject = "elasticemail-php: Integration test: validate email "
            . "attachment send.";
        $attachments = [
            __DIR__ . '/alpha-attachment.txt',
             __DIR__ . '/beta-attachment.txt'
        ];
        $elasticEmail = new ElasticEmail($_ENV['ELASTIC_EMAIL_API_KEY']);
        $response = $elasticEmail->email()->send([
            'to' => $_ENV['TEST_EMAIL_TO'],
            'from' => $_ENV['TEST_EMAIL_FROM'],
            'subject' => $subject,
            'bodyText' => 'Wake up Samurai!',
        ], $attachments);
```

**Comment by muzammilaskari** [comment]
Ah - Thanks man
You saved my day 
Cheers

**Comment by rdok** [comment]
Thanks for using this package; please feel free to point any bugs/additional high used features to enable from the [ElasicEmail API](http://api.elasticemail.com/public/help).
