### ISSUE TITLE
Read Receipts Option

### ISSUE THREAD

**Issue by muzammilaskari** [rdok/elasticemail-php#18]
Hi,
First of all thank you so much for such a great package.
I need to know how do we add option for allowing read receipts reply?

**Comment by rdok** [comment]
Hey, 
You're welcome.

Are you asking for setting the reply to email? If so, it can be set using the `replyTo`:
 ```
$elasticEmail->email()->send([
    'to'      => 'to_email',
    'subject' => 'subject',
    'from'    => 'from_email',
    'replyTo' => 'reply_email'
]);
```

This package forwards any parameters as per the ElasticEmail API http://api.elasticemail.com/public/help#Email_Send

**Comment by muzammilaskari** [comment]
Hey, 
I am asking for delivery email receipts,

**Comment by rdok** [comment]
@muzammilaskari https://github.com/rdok/elasticemail-php/wiki/Examples#how-do-i-get-the-status-an-email-sent

**Comment by muzammilaskari** [comment]
@rdok thanks for your answer but I need to add option for automatic delivery email receipts to custom email address

**Comment by rdok** [comment]
>  but I need to add option for automatic delivery email receipts to custom email address

This is outside the scope of this library. 

It aims to just provide PHP sugar functions for interacting with http://api.elasticemail.com/public/help API  endpoints.  

Feel free to request any API endpoint not yet supported.
