### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by jkrassman** [rdok/elasticemail-php#9]
Hi, I am maybe stupid but this is the first time I am using composer and I did manage to install the packages with no problems.

Problem is that I cant execute the sample code. The server is returning a error.

Fatal error: Using $this when not in object context in C:\Webbar\nextGen\test.php on line 24

Regards, Joakim

**Comment by rdok** [comment]
hello @jkrassman 

Thanks for the report. 

Yeah, you were right. My bad. The readme had a mistake. See https://github.com/rdok/elasticemail-php/commit/a42f5c19dcf95dfc1c1a857230868c066b6fe0a8 

The correct example code is:

```
$elasticEmail = new \ElasticEmail\ElasticEmailV2('your_elastic_api_key');

$elasticEmail->email()->send([
   'to'      => 'to_email',
   'subject' => 'subject',
   'from'    => 'from_email'
]);
```

Regards,
Rizart
